// <auto-generated />
using System;
using KartAdminService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KartAdminService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AdminDbContext))]
    [Migration("20260811003058_AddAdminActionTraceParent")]
    partial class AddAdminActionTraceParent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KartAdminService.Domain.Actions.AdminAction", b =>
                {
                    b.Property<Guid>("ActionId")
                        .HasColumnType("uuid")
                        .HasColumnName("action_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("AdminId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("admin_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Context")
                        .HasColumnType("jsonb")
                        .HasColumnName("context");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_id");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset>("PerformedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("PublishedBy")
                        .HasColumnType("text")
                        .HasColumnName("published_by");

                    b.Property<string>("TraceParent")
                        .HasColumnType("text")
                        .HasColumnName("trace_parent");

                    b.HasKey("ActionId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("uq_admin_actions_idempotency_key");

                    b.HasIndex("PerformedAt")
                        .HasDatabaseName("idx_admin_actions_unpublished")
                        .HasFilter("published_at IS NULL");

                    b.HasIndex("AdminId", "Category", "PerformedAt")
                        .HasDatabaseName("idx_admin_actions_admin_category");

                    b.ToTable("admin_actions", null, t =>
                        {
                            t.HasCheckConstraint("ck_admin_actions_category", "category IN ('catalog-management','coupon-issuance','user-suspension','inventory-replenishment','permission-management')");
                        });
                });

            modelBuilder.Entity("KartAdminService.Domain.PermissionGrants.AdminPermissionGrant", b =>
                {
                    b.Property<Guid>("GrantId")
                        .HasColumnType("uuid")
                        .HasColumnName("grant_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<string>("GrantedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("granted_by");

                    b.Property<string>("PrincipalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("principal_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedBy")
                        .HasColumnType("text")
                        .HasColumnName("revoked_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("GrantId");

                    b.HasIndex("PrincipalId", "Category")
                        .IsUnique()
                        .HasDatabaseName("uq_admin_permission_grants_live")
                        .HasFilter("revoked_at IS NULL");

                    b.ToTable("admin_permission_grants", null, t =>
                        {
                            t.HasCheckConstraint("ck_admin_permission_grants_category", "category IN ('catalog-management','coupon-issuance','user-suspension','inventory-replenishment','permission-management')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
